#!/usr/bin/env bash

if [ -f ./install ]; then

  if [ -f ~/.alias  ] && [ ! -L ~/.alias  ]; then
    echo 'mv ~/.alias ~/.alias_bis'
    mv ~/.alias ~/.alias_bis
  fi

  if [ -f ~/.zshenv ] && [ ! -L ~/.zshenv ]; then
    echo 'mv ~/.zshenv ~/.zshenv_bis'
    mv ~/.zshenv ~/.zshenv_bis
  fi

  links=`cat $1`
  for l in $links; do
    mkdir -p ~/`dirname $l`
    echo "ln -fs `pwd`/$l ~/`dirname $l`/"
    ln -fs `pwd`/$l ~/`dirname $l`/
  done

  echo "Compiling xterm-256color-italic terminfo..."
  tic xterm-256color-italic.terminfo

else
  echo "ERROR: you must run this script within the .dotfiles directory!"
fi

# vim: tabstop=2 shiftwidth=2
