#!/usr/bin/env bash

if [ -f ./install ]; then

  if [ -f ~/.alias  ] && [ ! -L ~/.alias  ]; then
    echo 'mv ~/.alias ~/.alias_bis'
    mv ~/.alias ~/.alias_bis
  fi

  if [ -f ~/.zshenv ] && [ ! -L ~/.zshenv ]; then
    echo 'mv ~/.zshenv ~/.zshenv_bis'
    mv ~/.zshenv ~/.zshenv_bis
  fi

  while read -r line; do
    file=`echo $line | sed 's/ .*//g'`
    dest=`echo $line | sed 's/.* //g'`

    mkdir -p ~/`dirname $dest`

    if [[ $dest == $file ]]; then
      echo "ln -fs `pwd`/$file $HOME/`dirname $file`"
      ln -fs `pwd`/$file $HOME/`dirname $file`
    else
      echo "ln -fs `pwd`/$file $dest"
      ln -fs `pwd`/$file "${dest/#\~/$HOME}"
    fi
  done < $1

  echo "Compiling xterm-256color-italic terminfo..."
  tic xterm-256color-italic.terminfo

else
  echo "ERROR: you must run this script within the .dotfiles directory!"
fi

# vim: tabstop=2 shiftwidth=2
