#!/bin/bash

if [[ $(pacmd list-sinks | awk '/muted/ { print $2 }') == "yes" ]]; then
    echo 0! > /tmp/xobpipe
else
    level=$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)
    echo $level > /tmp/xobpipe
fi

