#!/bin/sh

top_padding=34
bottom_padding=29

bspc config border_width 2
bspc config window_gap 7
bspc config top_padding $top_padding

bspc config split_ratio 0.5
bspc config gapless_monocle true
bspc config top_monocle_padding -$top_padding

bspc rule -a kitty rectangle=200x200
bspc rule -a Google-chrome desktop=^10 follow=on
bspc rule -a TelegramDesktop desktop=^9 follow=on
bspc rule -a 'whatsapp-nativefier-d52542' desktop=^9 follow=on
bspc rule -a Gimp state=floating
bspc rule -a Inkscape state=floating
bspc rule -a Skype state=floating
bspc rule -a zoom state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a itunes.exe state=floating
bspc rule -a ROOT state=floating

killall sxhkd

if [[ `hostname` == "hackintosh" ]]; then

    sxhkd -m -1 ~/.config/sxhkd/sxhkdrc.hackintosh &
    bspc monitor -d I II III IV V VI VII VIII IX X XI XII

    # bspc config bottom_padding -7
    # bspc config left_padding -7
    # bspc config right_padding -7
    bspc config bottom_padding $bottom_padding

elif [[ `hostname` == "lxpertoldi" ]]; then

    sxhkd ~/.config/sxhkd/sxhkdrc.lxpertoldi &
    bspc monitor DP-2 -d I II III IV V VI VII VIII IX X
    bspc monitor DP-1 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX

    bspc rule -a Google-chrome desktop=^19 follow=on
    bspc rule -a TelegramDesktop desktop=^18 follow=on
    bspc rule -a 'whatsapp-nativefier-d52542' desktop=^18 follow=on

else

    bspc monitor -d I II III IV V VI VII VIII IX X
    sxhkd &

fi

$HOME/.config/polybar/launch.sh
